name: WeeklyBudget
configs:
  Debug: debug
  Release: release
targetTemplates:
  WeeklyBudgetBase:
    type: application
    platform: iOS
    deploymentTarget: 10.0
    scheme:
#      testTargets:
#        - WeeklyBudgetTests
      gatherCoverageData: true
    sources:
      - path: WeeklyBudget
        excludes:
          - "**/*.md" # excludes all files with the .md extension
    settings:
      base:
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_STYLE: Manual
        MARKETING_VERSION: 1.0.0
        SWIFT_VERSION: 5.2
        SWIFT_OPTIMIZATION_LEVEL: "-Onone"
        TARGETED_DEVICE_FAMILY: 1
        DEVELOPMENT_TEAM: ""
        ENABLE_BITCODE: false
        LIBRARY_SEARCH_PATHS:
          - "$(inherited)"
          - "$(PROJECT_DIR)/WeeklyBudget"
    # In case need any dependencies
    # dependencies:
    #   - sdk: UIKit.framework
    #   - framework: AnyFramework.framework
    #     embed: false
    #     link: true
    #     codeSign: false
    postBuildScripts:
      - script: |
                echo "post build scripts"
        name: "Echo Post Build Scripts"
targets:
  WeeklyBudget:
    templates:
      - WeeklyBudgetBase
    settings:
      base:
        INFOPLIST_FILE: WeeklyBudget/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.LukmanSp.WeeklyBudget
  WeeklyBudgetStage:
    templates:
      - WeeklyBudgetBase
    settings:
      base:
        INFOPLIST_FILE: WeeklyBudget/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.LukmanSp.WeeklyBudget.stage
      configs:
        Debug:
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: STAGE DEBUG
        Release:
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: STAGE
#  WeeklyBudgetTests:
#    type: bundle.unit-test
#    platform: iOS
#    deploymentTarget: "10.0"
#    dependencies:
#      - target: WeeklyBudget
#    settings:
#      CODE_SIGN_STYLE: Manual
#      SWIFT_VERSION: "5.2"
#      INFOPLIST_FILE: WeeklyBudgetBase/Info.plist
#      TEST_HOST: $(BUILT_PRODUCTS_DIR)/WeeklyBudget.app/WeeklyBudget
#    scheme:
#      testTargets:
#        - WeeklyBudgetTests
#      gatherCoverageData: true
#    sources:
#      - path: WeeklyBudgetTests

